name: Continuous Integration

on:
  push:
    paths:
      - 'packages/contract/contracts/**'
    branches:
      - main

env:
  MNEMONIC: ${{ secrets.MNEMONIC }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn contract:test

      - name: Generate coverage report
        run: yarn contract:coverage
        
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}