name: upload file to upx

on:
  # 手动触发事件
  workflow_dispatch:

jobs:
  upx-uoloader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Build Upx
        run: |
          git clone https://github.com/upyun/upx.git && cd upx && make

      - name: Sync files to UPYUN
        env:
          UPYUN_SERVICE: ${{ env.UPYUN_SERVICE }}
          UPYUN_OPERATOR: ${{ env.UPYUN_OPERATOR }}
        run: |
          upx --service $UPYUN_SERVICE \
              --operator $UPYUN_OPERATOR \
              --password ${{ secrets.UPYUN_PASSWORD }} \
              sync ./imgs .
      