name: upload file to upx

on:
  # 手动触发事件
  workflow_dispatch:

jobs:
  upx-uoloader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install upx tool
        run: |
          curl -LJO --progress-bar https://collection.b0.upaiyun.com/softwares/upx/upx_0.3.6_linux_x86_64.tar.gz && tar xvzf upx_0.3.6_linux_x86_64.tar.gz
          chmod +x upx

      - name: Sync files to UPYUN
        env:
        run: ./upx login ${{ vars.UPYUN_SERVICE }} ${{ vars.UPYUN_OPERATOR }} ${{ secrets.UPYUN_PASSWORD }}  && ./upx sync ./imgs .

      