name: vue deplpy

on:
  push:
    paths:
      - 'packages/vue-app/src/**'
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PRIVATE_KEY_PHRASE:  ${{ secrets.KEY_PASSPHRASE }}
  REMOTE_SERVER: ${{ secrets.REMOTE_SERVER }}
  REMOTE_USER: ${{ secrets.REMOTE_USER }}
  REMOTE_DIR: "/home/pili/code/github-action/packages/vue-app"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Deploy code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_SERVER }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          passphrase: ${{ env.SSH_PRIVATE_KEY_PHRASE }}
          script: |
            cd ${{ env.REMOTE_DIR }}
            git pull
            npm install
            npm run build